name = "Deneb"
uuid = "b5a61f88-a05b-4725-9526-4eca17cec623"
authors = ["brucala <brucala@gmail.com>"]
version = "0.2.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MultilineStrings = "1e8d2bf6-9821-4900-9a2f-4d87552df2bd"
NodeJS_18_jll = "c1e1d063-8311-5f52-a749-c7b05e91ae37"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
JSON = "0.21"
MultilineStrings = "0.1.1"
Tables = "1"
julia = "1.6"
